version: '3.5'
services:
    BMHORARIOUI:
        build:
            context: .
            dockerfile: Dockerfile
        image: business-manager-horario-ui
        expose:
            - 9001
        ports:
            - 9001:9001
        labels:
            NAME: "business-manager-horario-ui"
        tty: true
networks:
    default:
        external:
            name: BM_NETWORK